version: '3.8'

services:
  bun:
    build: .
    container_name: bun_server
    ports:
      - "6969:6970"
    env_file:
      - .env
    networks:
      - bun_network
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production
    extra_hosts:
      - "minio_images:172.17.0.1"  # Docker host IP

networks:
  bun_network:
    name: bun_network
    driver: bridge

volumes:
  minio_data: 