version: '3.8'

services:
  bun:
    build: .
    container_name: bun_server
    network_mode: "host"  # Use host network to access MinIO on localhost
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - NODE_ENV=production

volumes:
  minio_data: 