version: '3.8'

services:
  bun:
    build: .
    container_name: bun_server
    ports:
      - "6969:6970"
    env_file:
      - .env
    networks:
      - bun_network
    restart: unless-stopped

networks:
  bun_network:
    name: bun_network
    driver: bridge

volumes:
  minio_data: 