version: '3.8'

services:
  bun:
    build: .
    ports:
      - "6969:6970"
    environment:
      - S3_ACCESS_KEY_ID=QFd9YsPxT4LAPwokJlmc
      - S3_SECRET_ACCESS_KEY=A6uBAfXdJEPoy1F7m0QSnAxIXwzqR8Nj0hR
      - S3_ENDPOINT=http://cdn.vrugle.com:9000
    networks:
      - app-network
    external_links:
      - minio_images:minio

networks:
  app-network:
    external: true  # Use existing network

volumes:
  minio_data: 